#!/usr/bin/env bash -e
# Applies default preferences for macOS and some apps.
source $HOME/.dotfiles/.dot/dot/env

if [[ "$OS" != "Darwin" ]]; then
  pprint step-error "This is not a Mac"
  exit 1
fi

pprint section "Applying system defaults"

$DOT/macos/defaults.sh
