#!/usr/bin/env bash
# Generates .gitconfig.symlink
source $HOME/.dotfiles/.dot/dot/env

if [[ -f git/gitconfig.local.symlink ]]; then
  exit 0
fi

pprint section 'SETTING UP GITCONFIG'

git_credential='cache'
if [ "$OS" == "Darwin" ]; then
  git_credential='osxkeychain'
fi

s_credential="s/GIT_CREDENTIAL_HELPER/${git_credential}/g"
sed -e "${s_credential}" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

pprint step-ok -r 'gitconfig generated'
pprint newline
