#!/usr/bin/env bash
# Configures your shell

set -e
source $HOME/.dotfiles/.dot/dot/env

pprint section "PREPARING SHELL"

if [[ $(basename $SHELL) != 'zsh' ]]; then
  pprint step-go "Setting ZSH as your shell..."
  sudoplz

  if [[ $? == 0 ]]; then
    sudo chsh -s $(which zsh) $(whoami) 2> /dev/null
    pprint info-ok -n "She sells z shells"
  fi
fi

pprint step-ok -n "Your shell is properly configured"
