alias dcompose='docker-compose'
alias docker-vm='screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty'
alias k='kubectl'
alias kk='kubectl apply -k'
alias kkk='kubectl apply -k .'
