#!/usr/bin/env bash
# This hook is run during the startup phase when loading virtualenvwrapper.sh.

function generate_venv_file {
    virtualenvwrapper_verify_workon_home || return 1
    virtualenvwrapper_verify_active_environment || return 1
    if [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" ]; then
        typeset project_dir="$(cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME")"
        if [ ! -z "$project_dir" ]; then
            echo `basename $VIRTUAL_ENV` > "$project_dir/.venv"
        else
            echo "Project directory $project_dir does not exist" 1>&2
            return 1
        fi
    else
        echo "No project set in $VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" 1>&2
        return 1
    fi
    return 0
}

function workon_venv {
    venv=`findup .venv`
    if [[ -n $venv ]]; then
        echo "Moving onto virtualenv"
        workon `cat $venv`
    fi
}

# enable checking for virtualenv on cd
workon_venv
