#!/usr/local/bin/zsh
# This hook is run after every virtualenv is activated.

# It overrides cd to know about the VENV
# Instead of doing cd to go to ~ you will go to the venv root
cd() {
    if (( $# == 0 )); then
        builtin cd $VIRTUAL_ENV
    else
        builtin cd "$@"
    fi
}
