#!/usr/local/bin/zsh
# This hook is run after every virtualenv is activated.

# Make sure projects always have an updated .venv file
if [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" ]; then
    typeset project_dir="$(cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME")"
    if [ ! -f "$project_dir/.venv" ]; then
        generate_venv_file
    elif [ `cat $project_dir/.venv` != `basename $VIRTUAL_ENV` ]; then
        generate_venv_file
    fi
fi
