#!/usr/bin/env bash
# Installs your apps from Homebrew Cask

# Init environment
source $HOME/.dotfiles/.dot/util/env

if [[ "$(uname -s)" != "Darwin" ]]; then
  pprint fail "This is not a Mac"
  pprint flush
  exit 1
fi

pprint intro "Installing apps"
pprint flush

$DOT/cask/apps.sh
pprint flush
exit 0
