#!/usr/bin/env bash
# Installs your apps from Homebrew Cask

# Init environment
source $HOME/.dotfiles/.dot/util/env

if [[ "$(uname -s)" != "Darwin" ]]; then
  pprint step-error "This is not a Mac"
  pprint newline
  exit 1
fi

pprint section "Installing apps"
pprint newline

$DOT/cask/apps.sh
pprint newline
exit 0
