#!/usr/bin/env bash
#
# Applies default preferences of your OS and some apps.

# Init environment
source $HOME/.dotfiles/.dot/util/env

# Set OS X defaults
if [[ "$(uname -s)" == "Darwin" ]]; then
  $DOT/osx/defaults.sh
fi
