#!/usr/bin/env bash
#
# Checks and install dependencies for the defaults step.

# Init environment
source $HOME/.dotfiles/.dot/util/env

# Install osx apps
if [[ "$(uname -s)" == "Darwin" ]]; then
  $DOT/cask/defaults.dep.sh
fi

