#!/usr/bin/env bash
# Applies default preferences for OSX and some apps.

set -e

# Init environment
source $HOME/.dotfiles/.dot/util/env

if [[ "$(uname -s)" != "Darwin" ]]; then
  pprint step-error "This is not a Mac"
  exit 1
fi

pprint section "Applying system defaults"

$DOT/osx/defaults.sh
exit 0
