#!/usr/bin/env bash
# Welcomes and initializes submodules

set -e

# Init environment
source $HOME/.dotfiles/.dot/util/env

echo
echo "   ██████   ██████  ████████ ███████ ██ ██      ███████ ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██      ██     "
echo "   ██   ██ ██    ██    ██    █████   ██ ██      █████   ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██           ██"
echo "██ ██████   ██████     ██    ██      ██ ███████ ███████ ███████"
echo "                                              Let's do(t) this!"

pprint intro "READY TO START?"

git submodule init
git submodule update
pprint success "All submodules in place"

pprint flush
exit 0
