#!/usr/bin/env bash
# Debriefing splash

# Init environment
source $HOME/.dotfiles/.dot/util/env

pprint success "Dotfiles @ home"
pprint ok "Restart your terminal"
pprint ok "Run \`dot ossetup\` to get your GUI realm ready"
