#!/usr/bin/env bash
# Debriefing splash

# Init environment
source $HOME/.dotfiles/.dot/util/env

pprint intro   "EVERYTHING READY!"
pprint success "What to do now?"
pprint step    "1) Open a new terminal"
pprint step    "2) Antigen will download some plugins for ZSH"
pprint step    "3) Run \`dot osxsetup\` if you want to set up your Mac"
pprint ok      "4) PROFIT! Enjoy your system now ;)"
pprint flush
pprint flush
