#!/usr/bin/env bash
# Welcomes and initializes submodules

set -e

# Init environment
source $HOME/.dotfiles/.dot/util/env

echo
echo "   ██████   ██████  ████████ ███████ ██ ██      ███████ ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██      ██     "
echo "   ██   ██ ██    ██    ██    █████   ██ ██      █████   ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██           ██"
echo "██ ██████   ██████     ██    ██      ██ ███████ ███████ ███████"
echo "                                              Let's do(t) this!"
echo

init_submodules() {
  git submodule init 2> /dev/null
  git submodule update 2> /dev/null
}

init_submodules
pprint flush
exit 0
