#!/usr/bin/env bash
# Runs all topic installers

# Init environment
source $HOME/.dotfiles/.dot/util/env

pprint intro 'RUNNING INSTALLERS'

# Prepare logs
logsuffix='.install.dot.log'
find -L /tmp -maxdepth 1 -name *${logsuffix} | while read logfile; do rm "${logfile}"; done

# Find and run install scripts
for script in $(find $DOT -maxdepth 2 -name install.sh); do
  topic=`basename $(dirname ${script})`
  export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
  pprint info "Installing stuff for ${topic}..."
  sh -c "${script}"
  [[ $? == 0 ]] && pprint ok "All is done"
  [[ $? != 0 ]] && errors+=(${topic}) && pprint error "Failed"
  pprint flush
done

# Show summary
if [[ ${errors} ]]; then
  plogs ${logsuffix} ${errors[@]}
else
  pprint success "Everything installed"
fi

pprint flush
exit 0
