#!/usr/bin/env bash
#
# Checks and install dependencies for the install step.

pprint intro 'Checking dependencies'

# Init environment
source $HOME/.dotfiles/.dot/util/env

# Prepare logs
logfile_suffix='.install.dep.dot.log'
find -L /tmp -maxdepth 1 -name *$logfile_suffix | while read logfile; do rm "$logfile"; done

# TODO: define order of dependencies (python depends on homebrew)
# Find and run dependency install scripts
for script in `find $DOT -maxdepth 2 -name install.dep.sh`; do
  topic=`basename $(dirname ${script})`
  export DOT_TOPIC_LOGFILE_SUFFIX=$topic$logfile_suffix
  pprint info "Checking dependencies from $topic..."
  sh -c "$script"
  [[ $? == 0 ]] && pprint ok "All is ready"
  [[ $? != 0 ]] && errors+=($topic) && pprint error "Missing"
  pprint flush
done

# Show summary
if [[ $errors ]]; then
  print_error_logs $errors $logfile_suffix
else
  pprint success "All dependencies are ready"
fi

pprint flush
exit 0
