#!/usr/bin/env bash
# Configures your shell on a clean SO install.

set -e

# Init environment
source $HOME/.dotfiles/.dot/util/env

pprint intro "PREPARING SHELL"

# Make ZSH the default login shell
if [[ $(basename $SHELL) != 'zsh' ]]; then
  pprint user "Setting ZSH as your shell"
  pprint flush
  pprint flush
  chsh -s $(which zsh)
fi

# Activate root user in Mac
if [ "$(uname -s)" == "Darwin" ]; then
  pprint user "Activating root user now (you will need \`sudo\` later)"
  pprint flush
  sudo echo > /dev/null
fi

pprint success "Your shell is properly configured"
pprint flush
exit 0
