#!/usr/bin/env bash
#
# Initializes some things on a clean SO install.

# TODO: Add introduction text?

# Make ZSH the default login shell
chsh -s $(which zsh)

# Activate root user in Mac
if [ "$(uname -s)" == "Darwin" ]; then
	sudo echo "root user activated"
fi
