#!/usr/bin/env bash -e
# Applies default preferences for OSX and some apps.
source $HOME/.dotfiles/.dot/env

if [[ "$(uname -s)" != "Darwin" ]]; then
  pprint step-error "This is not a Mac"
  exit 1
fi

pprint section "SETTING OSX DEFAULTS"

# Ask for the administrator password upfront
sudoplz -k -s -r "Needed not to bother you later"
pprint newline

$DOT/osx/defaults.sh
