#!/usr/bin/env bash -e
# Applies default preferences for OSX and some apps.
source $HOME/.dotfiles/.dot/env

if [[ "$(uname -s)" != "Darwin" ]]; then
  pprint step-error "This is not a Mac"
  exit 1
fi

pprint section "Applying system defaults"

$DOT/osx/defaults.sh
