#!/usr/bin/env bash
# Welcomes and initializes submodules

set -e
source $HOME/.dotfiles/.dot/env

echo
echo "   ██████   ██████  ████████ ███████ ██ ██      ███████ ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██      ██     "
echo "   ██   ██ ██    ██    ██    █████   ██ ██      █████   ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██           ██"
echo "██ ██████   ██████     ██    ██      ██ ███████ ███████ ███████"
echo "                                              Let's do(t) this!"

pprint section "READY TO START?"

git submodule init
git submodule update

pprint step-ok "All submodules in place"
pprint newline
