#!/usr/bin/env bash
# Welcomes and initializes submodules

set -e
source $HOME/.dotfiles/.dot/env

git submodule init
git submodule update

echo
echo "   ██████   ██████  ████████ ███████ ██ ██      ███████ ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██      ██     "
echo "   ██   ██ ██    ██    ██    █████   ██ ██      █████   ███████"
echo "   ██   ██ ██    ██    ██    ██      ██ ██      ██           ██"
echo "██ ██████   ██████     ██    ██      ██ ███████ ███████ ███████"
echo "                                              Let's do(t) this!"

pprint section "READY TO START?"
pprint step-ok -n "All submodules in place"

# Ask for sudo early on so that the rest is unattended
sudoplz -k -s -r "For unattended install (optional)" || true
