#!/usr/bin/env bash
# Checks and install dependencies for the install step
source $HOME/.dotfiles/.dot/env

pprint section 'CHECKING DEPENDENCIES'

# Prepare logs
logsuffix='.install.dep.dot.log'
find -L /tmp -maxdepth 1 -name *${logsuffix} | while read logfile; do rm "${logfile}"; done

# Order of topic dependencies
topics='system homebrew'

# Find and run dependency install scripts
for script in $(dotfind install.dep.sh --priority ${topics}); do
  # Refresh environment before each topic
  source $HOME/.dotfiles/.dot/env
  topic=`basename $(dirname ${script})`
  export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
  pprint step-go "Checking dependencies from ${topic}..."
  sh -c "${script}"
  [[ $? == 0 ]] && pprint info-ok -n "All is ready"
  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error -n "Missing" && break
done

# Show summary
if [[ ${errors} ]]; then
  plogs ${logsuffix} ${errors[@]}
  exit 1
else
  pprint step-ok -n "All dependencies are ready"
  exit 0
fi
