#!/usr/bin/env bash
# Checks and install dependencies for the install step
source $HOME/.dotfiles/.dot/env

pprint section 'CHECKING DEPENDENCIES'

# Prepare logs
logsuffix='.install.dep.dot.log'
find -L /tmp -maxdepth 1 -name *${logsuffix} | while read logfile; do rm "${logfile}"; done

# TODO: define order of dependencies (e.g. python depends on homebrew)
# Find and run dependency install scripts
for script in $(find $DOT -maxdepth 2 -name install.dep.sh); do
  topic=`basename $(dirname ${script})`
  export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
  pprint step-go "Checking dependencies from ${topic}..."
  sh -c "${script}"
  [[ $? == 0 ]] && pprint info-ok "All is ready"
  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error "Missing"
  pprint newline
done

# Show summary
if [[ ${errors} ]]; then
  plogs ${logsuffix} ${errors[@]}
  exit 1
else
  pprint step-ok "All dependencies are ready"
  pprint newline
  exit 0
fi
