#!/usr/bin/env bash
# Runs all topic installers
source $HOME/.dotfiles/.dot/env

pprint section 'RUNNING INSTALLERS'

# Prepare logs
logsuffix='.install.dot.log'
find -L /tmp -maxdepth 1 -name *${logsuffix} | while read logfile; do rm "${logfile}"; done

# Find and run install scripts
for script in $(find $DOT -maxdepth 2 -name install.sh | sort); do
  topic=`basename $(dirname ${script})`
  export DOT_TOPIC_LOGFILE_SUFFIX=${topic}${logsuffix}
  pprint step-go "Installing stuff for ${topic}..."
  sh -c "${script}"
  [[ $? == 0 ]] && pprint info-ok "All is done"
  [[ $? != 0 ]] && errors+=(${topic}) && pprint info-error "Failed"
  pprint newline
done

# Show summary
if [[ ${errors} ]]; then
  plogs ${logsuffix} ${errors[@]}
else
  pprint step-ok "Everything installed"
  pprint newline
fi

exit 0
