#!/usr/bin/env bash
# Configures your shell on a clean SO install

set -e
source $HOME/.dotfiles/.dot/env

pprint section "PREPARING SHELL"

# Make ZSH the default login shell
if [[ $(basename $SHELL) != 'zsh' ]]; then
  sudoplz
  sudo chsh -s $(which zsh) $(whoami) 2> /dev/null
  pprint step-ok "ZSH set as your shell"
  pprint newline
fi

pprint step-ok "Your shell is properly configured"
pprint newline
