#!/usr/bin/env bash
# Configures your shell on a clean SO install

set -e
source $HOME/.dotfiles/.dot/env

pprint section "PREPARING SHELL"


# Install stuff for Linux
if [[ "$(uname -s)" == "Linux" ]]; then
  pprint step-user "Preparing Linux"
  pinstall apt build-essential
  pinstall apt ruby
  pinstall apt zsh
fi

# Make ZSH the default login shell
if [[ $(basename $SHELL) != 'zsh' ]]; then
  pprint step-user "Setting ZSH as your shell"
  pprint newline
  pprint newline
  chsh -s $(which zsh)
fi

# Activate root user in Mac
if [[ "$(uname -s)" == "Darwin" ]]; then
  pprint step-user "Activating root user now (you will need \`sudo\` later)"
  pprint newline
  sudo echo > /dev/null
fi

pprint step-ok "Your shell is properly configured"
pprint newline
